lang: ja_JP
title: bearsworld
description: for friendbear GitHub Pages.
show_downloads: false
# Social Sharing
twitter:
  username: friendbear22
facebook:
  username: friendbear22
  app_id:
  publisher:
# For specifying social profiles
social:
  type:
  name:
  links:
#hubspot: true
theme: jekyll-theme-architect
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:categories/:year/:month/:day/:title:output_ext
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: friendbear

analytics:
  provider: "google"
  google:
    tracking_id: UA-37353976-3
    anonymize_ip: false

comments: true

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

        # Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/friendbear22"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/friendbear22"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/friendbear"
        #    - label: "YouTube"
        #      icon: "fab fa-fw fa-youtube"
        #      url: "https://youtube.com/rockthejvm"

# Reading Files
include:
include:
  - .htaccess
  - node_modules/uglifier/index.js
  - _pages
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - jekyll-paginate
  - jekyll-assets
  - jekyll-youtube
  - jekyll-seo-tag

